"""Streamlit UI: pipeline progress, findings, PoC highlighting, report download."""

from __future__ import annotations

import logging

import streamlit as st

from auditor.config import STAGES, get_settings
from auditor.errors import AuditorError
from auditor.logging_setup import setup_logging
from auditor.models import AuditResult, Finding, FindingStatus, Severity
from auditor.orchestrator import run_audit, stage_label
from auditor.util import validate_address

logger = logging.getLogger(__name__)

_SEVERITY_COLORS = {
    Severity.CRITICAL: ("#7f1d1d", "#fecaca"),
    Severity.HIGH: ("#9a3412", "#fed7aa"),
    Severity.MEDIUM: ("#854d0e", "#fde68a"),
    Severity.LOW: ("#3f3f46", "#e4e4e7"),
}

_STATUS_COLORS = {
    FindingStatus.CONFIRMED: ("#14532d", "#bbf7d0"),
    FindingStatus.UNCONFIRMED: ("#78350f", "#fde68a"),
    FindingStatus.STATIC_ONLY: ("#1e293b", "#cbd5e1"),
}


def render_app() -> None:
    """Render the full Streamlit page. Called from the root ``app.py``."""
    st.set_page_config(
        page_title="Multi-Agent Contract Auditor",
        page_icon="⬡",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    setup_logging()
    _inject_css()

    with st.sidebar:
        st.markdown("### How confirmation works")
        st.markdown(
            "Critical and High candidates get a Foundry exploit **test** generated by "
            "an LLM. The test runs on a **local mainnet fork** — never on the live chain. "
            "A passing test marks the finding **CONFIRMED via PoC**. A revert or failed "
            "assertion is treated as a likely false positive."
        )
        st.markdown("### Prerequisites")
        st.markdown(
            "- Foundry (`forge`)\n"
            "- `uv tool install solc-select`\n"
            "- `.env` with `OPENAI_API_KEY`, `ETHERSCAN_API_KEY`, `INFURA_URL`"
        )
        st.caption("Automated first-pass tool. Confirmed findings still need human review.")

    st.markdown('<div class="hero">', unsafe_allow_html=True)
    st.markdown("# Multi-Agent Smart Contract Auditor")
    st.markdown(
        '<p class="subtitle">Fetch verified source · Slither · LLM triage · '
        "confirm Critical/High issues with a Foundry fork PoC.</p>",
        unsafe_allow_html=True,
    )
    st.markdown("</div>", unsafe_allow_html=True)

    missing = _missing_secrets()
    if missing:
        st.warning(
            "Missing secrets: **"
            + ", ".join(missing)
            + "**. Copy `.env.example` to `.env` and fill in the keys, then restart the app."
        )

    with st.form("audit_form", clear_on_submit=False):
        col_addr, col_block = st.columns((3, 1))
        with col_addr:
            address = st.text_input(
                "Contract address",
                placeholder="0x…",
                help="A verified Ethereum mainnet contract.",
            )
        with col_block:
            fork_raw = st.text_input(
                "Fork block (optional)",
                placeholder="latest",
                help="Pin the mainnet fork. Leave empty to use the latest block.",
            )
        submitted = st.form_submit_button("Audit", type="primary", use_container_width=False)

    if submitted:
        _run_and_store(address, fork_raw)

    result: AuditResult | None = st.session_state.get("audit_result")
    error: str | None = st.session_state.get("audit_error")
    if error:
        st.error(error)
    if result:
        _render_results(result)


def _run_and_store(address: str, fork_raw: str) -> None:
    st.session_state.pop("audit_result", None)
    st.session_state.pop("audit_error", None)

    try:
        validate_address(address)
    except AuditorError as exc:
        st.session_state["audit_error"] = str(exc)
        return

    fork_block: int | None = None
    if fork_raw.strip():
        try:
            fork_block = int(fork_raw.strip())
        except ValueError:
            st.session_state["audit_error"] = "Fork block must be an integer."
            return
        if fork_block < 0:
            st.session_state["audit_error"] = "Fork block must be non-negative."
            return

    placeholders = _render_stage_placeholders()

    def on_progress(stage: str, status: str, detail: str) -> None:
        _fill_stage(placeholders, stage, status, detail)

    try:
        with st.spinner(
            "Auditing — fetching source, running Slither, then confirming Critical/High "
            "findings on a local fork. This often takes several minutes."
        ):
            result = run_audit(address.strip(), fork_block=fork_block, on_progress=on_progress)
        st.session_state["audit_result"] = result
    except AuditorError as exc:
        logger.warning("Audit failed: %s", exc)
        st.session_state["audit_error"] = str(exc)
    except Exception as exc:  # noqa: BLE001 — surface unexpected failures in the UI
        logger.exception("Unexpected audit failure")
        st.session_state["audit_error"] = f"Unexpected error: {exc}"


def _render_stage_placeholders() -> dict[str, object]:
    st.markdown("### Pipeline")
    placeholders: dict[str, object] = {}
    cols = st.columns(len(STAGES))
    for stage, col in zip(STAGES, cols, strict=True):
        with col:
            placeholders[stage] = st.empty()
            _fill_stage(placeholders, stage, "waiting", "queued")
    return placeholders


def _fill_stage(placeholders: dict[str, object], stage: str, status: str, detail: str) -> None:
    box = placeholders.get(stage)
    if box is None:
        return
    mark = {"waiting": "○", "running": "…", "done": "✓", "error": "✗"}.get(status, "·")
    css = status.replace(" ", "")
    label = stage_label(stage)
    caption = detail[:120] if detail else status
    box.markdown(
        f'<div class="stage stage-{css}"><div class="stage-mark">{mark}</div>'
        f'<div class="stage-label">{label}</div>'
        f'<div class="stage-detail">{_html_escape(caption)}</div></div>',
        unsafe_allow_html=True,
    )


def _render_results(result: AuditResult) -> None:
    confirmed = sum(1 for f in result.findings if f.status is FindingStatus.CONFIRMED)
    unconfirmed = sum(1 for f in result.findings if f.status is FindingStatus.UNCONFIRMED)
    static_only = sum(1 for f in result.findings if f.status is FindingStatus.STATIC_ONLY)

    st.markdown("### Results")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Findings", len(result.findings))
    c2.metric("Confirmed via PoC", confirmed)
    c3.metric("Unconfirmed", unconfirmed)
    c4.metric("Static-only", static_only)

    meta = f"**{result.contract_name}** · `{result.address}`"
    if result.is_proxy:
        meta += f" · proxy → `{result.implementation_address or 'unknown implementation'}`"
    if result.fork_block is not None:
        meta += f" · fork block `{result.fork_block}`"
    st.markdown(meta)
    if result.proxy_hint:
        st.caption(result.proxy_hint)
    if result.slither_error:
        st.info(f"Slither ran in degraded mode: {result.slither_error[:400]}")

    st.download_button(
        "Download report",
        data=result.report_markdown.encode("utf-8"),
        file_name=f"audit-{result.address[:10]}.md",
        mime="text/markdown",
    )

    tab_findings, tab_report, tab_slither = st.tabs(["Findings", "Full report", "Slither"])
    with tab_findings:
        if not result.findings:
            st.success("No candidate vulnerabilities were triaged.")
        for finding in result.findings:
            _render_finding(finding)
    with tab_report:
        st.markdown(result.report_markdown)
    with tab_slither:
        if not result.slither_findings:
            st.write("No Slither detector findings (or Slither did not run).")
        for item in result.slither_findings:
            loc = ""
            if item.filenames or item.lines:
                loc = f" — {', '.join(item.filenames[:2])} {item.lines[:6]}"
            with st.expander(f"[{item.impact}/{item.confidence}] {item.check}{loc}"):
                st.write(item.description or "(no description)")


def _render_finding(finding: Finding) -> None:
    sev_bg, sev_fg = _SEVERITY_COLORS[finding.candidate.severity]
    st_bg, st_fg = _STATUS_COLORS[finding.status]
    header = (
        f'<span class="badge" style="background:{sev_bg};color:{sev_fg}">'
        f"{finding.candidate.severity.value}</span> "
        f'<span class="badge" style="background:{st_bg};color:{st_fg}">'
        f"{finding.status_label}</span> "
        f"{finding.candidate.title}"
    )
    with st.expander(finding.candidate.title, expanded=finding.status is FindingStatus.CONFIRMED):
        st.markdown(header, unsafe_allow_html=True)
        st.markdown(finding.candidate.rationale)
        if finding.candidate.target_functions:
            st.caption("Functions: " + ", ".join(finding.candidate.target_functions))
        if finding.remediation:
            st.markdown("**Remediation**")
            st.markdown(finding.remediation)
        if finding.status is FindingStatus.CONFIRMED and finding.poc_code:
            st.markdown("**Passing PoC (Foundry fork test)**")
            st.code(finding.poc_code, language="solidity")
        elif finding.attempts:
            last = finding.attempts[-1]
            st.markdown(
                f"PoC not confirmed after {len(finding.attempts)} attempt(s). "
                "Treated as a likely false positive."
            )
            if last.revert_reason:
                st.code(last.revert_reason, language="text")
            if finding.poc_code:
                with st.expander("Last generated test"):
                    st.code(finding.poc_code, language="solidity")


def _missing_secrets() -> list[str]:
    settings = get_settings()
    missing: list[str] = []
    if not settings.openai_api_key:
        missing.append("OPENAI_API_KEY")
    if not settings.etherscan_api_key:
        missing.append("ETHERSCAN_API_KEY")
    if not settings.infura_url or "<key>" in settings.infura_url:
        missing.append("INFURA_URL")
    return missing


def _html_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _inject_css() -> None:
    st.markdown(
        """
        <style>
        .hero { margin-bottom: 1.4rem; }
        .subtitle { color: #94a3b8; font-size: 1.05rem; margin-top: -0.4rem; }
        .stage {
            background: rgba(148, 163, 184, 0.08);
            border: 1px solid rgba(148, 163, 184, 0.18);
            border-radius: 12px;
            padding: 0.75rem 0.8rem;
            min-height: 6.2rem;
        }
        .stage-mark { font-size: 1.1rem; color: #94a3b8; }
        .stage-label { font-weight: 650; margin-top: 0.2rem; }
        .stage-detail { color: #94a3b8; font-size: 0.78rem; margin-top: 0.25rem; }
        .stage-running { border-color: #38bdf8; }
        .stage-done { border-color: #34d399; }
        .stage-error { border-color: #f87171; }
        .badge {
            display: inline-block;
            padding: 0.1rem 0.5rem;
            border-radius: 999px;
            font-size: 0.75rem;
            font-weight: 650;
            margin-right: 0.35rem;
            letter-spacing: 0.01em;
        }
        div[data-testid="stForm"] {
            background: rgba(148, 163, 184, 0.06);
            border: 1px solid rgba(148, 163, 184, 0.16);
            border-radius: 16px;
            padding: 0.6rem 1rem 1rem 1rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )
